version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: notes_app
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
  
  user-db:
    image: mysql:5.7
    container_name: user-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: userdbpassword
      MYSQL_DATABASE: user_registration
      MYSQL_USER: user_admin
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./user-mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"

  web:
    build: ./apache
    container_name: apache-php
    ports:
      - "80:80"
    volumes:
      - ./apache:/var/www/html
    depends_on:
      - db
      - user-db

  admin:
    build: ./admin
    container_name: admin-site
    ports:
      - "81:80"
    volumes:
      - ./admin:/var/www/html
    depends_on:
      - db
      - user-db

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
      - user-db

  queue:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
