name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Этап сборки
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start containers
        run: |
          docker-compose -f ./docker-compose.yml up --build -d

      - name: Check containers status
        run: |
          docker-compose ps

  # Первый этап тестирования
  test-job-1:
    runs-on: ubuntu-latest
    needs: build-job  # Этот шаг выполняется только после успешного завершения build-job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose


  # Второй этап тестирования
  test-job-2:
    runs-on: ubuntu-latest
    needs: test-job-1  # Этот шаг выполняется только после успешного завершения test-job-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

          
  # Этап деплоя
  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job-2  # Этот шаг выполняется только после успешного завершения test-job-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Deploy to server
        run: |
          echo "Starting deployment..."
          sleep 2
          echo "Deployment completed successfully!"
