name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Этап сборки (Build)
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker images
        run: |
          docker-compose -f ./docker-compose.yml build

  # Этап тестирования (Test)
  test-job:
  runs-on: ubuntu-latest
  needs: build-job  # Этот шаг выполняется только после успешного завершения build-job

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Start containers for testing
      run: |
        docker-compose -f ./docker-compose.yml up -d
        docker ps  # Вывод списка запущенных контейнеров для проверки

    - name: Check container logs
      run: |
        docker-compose logs  

    - name: Run tests
      run: |
        docker-compose exec app npm test  
    - name: Clean up
      run: |
        docker-compose -f ./docker-compose.yml down


  # Этап деплоя (Deploy)
  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job  # Этот шаг выполняется только после успешного завершения test-job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Deploy to server
        run: |
          echo "Starting deployment..."
          sleep 2
          echo "Deployment completed successfully!"