name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build backend Docker image
      run: |
        docker build -t backend-image ./admin
        docker tag backend-image ghcr.io/f4aming/backend-image:latest  # Правильный формат тега

    - name: Build frontend Docker image
      run: |
        docker build -t frontend-image ./apache
        docker tag frontend-image ghcr.io/f4aming/frontend-image:latest  # Правильный формат тега

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker images
      run: |
        docker push ghcr.io/f4aming/backend-image:latest  # Правильный путь
        docker push ghcr.io/f4aming/frontend-image:latest  # Правильный путь

    - name: Deploy to Production
      run: |
        # Пример деплоя через SSH
        ssh -o StrictHostKeyChecking=no user@yourserver.com << 'EOF'
          docker pull ghcr.io/f4aming/backend-image:latest
          docker pull ghcr.io/f4aming/frontend-image:latest
          docker-compose down
          docker-compose up -d
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
