name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build backend Docker image
      run: |
        docker build -t backend-image ./app/backend
        docker tag backend-image $GITHUB_REGISTRY_URL/backend-image:latest

    - name: Build frontend Docker image
      run: |
        docker build -t frontend-image ./public
        docker tag frontend-image $GITHUB_REGISTRY_URL/frontend-image:latest

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker images
      run: |
        docker push $GITHUB_REGISTRY_URL/backend-image:latest
        docker push $GITHUB_REGISTRY_URL/frontend-image:latest

    - name: Deploy to Production
      run: |
        # Здесь добавьте команды для деплоя
        # Например, можно использовать Ansible, SCP, или деплой в Kubernetes
        # Пример деплоя через SSH:
        ssh -o StrictHostKeyChecking=no user@yourserver.com << 'EOF'
          docker pull $GITHUB_REGISTRY_URL/backend-image:latest
          docker pull $GITHUB_REGISTRY_URL/frontend-image:latest
          docker-compose down
          docker-compose up -d
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
